version: '3'

services:
  web:
    restart: always
    build: ./
    expose:
      - "8000"
    links:
      - db:db
    volumes:
      - web-data:/usr/src/app/static
    env_file: 
      - .env
    command: /usr/local/bin/gunicorn -w 2 -b :8000 wsgi:app

  nginx:
    restart: always
    build: ./nginx
    ports:
      - "80:80"
    volumes:
      - .:/www/static
      - web-data:/usr/src/app/static
    links:
      - web:web

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'sebam'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'espoir'
      # You can use whatever password you like
      MYSQL_PASSWORD: '9874'
      # Password for root access
      MYSQL_ROOT_PASSWORD: '9874'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
  web-data:
